### ISSUE TITLE
[Browser] - Pouchdb-find not working on ~5.4.0 versions.

### ISSUE THREAD

**Issue by ronyrun** [nolanlawson/pouchdb-find#199]
Hello I made some tests, and pouchdb-find is properly working with the verson 5.3.2 of PouchDB
With ~5.4.0 version I got this error on Browser : 
`Cannot read property 'Promise' of undefine`

![image](https://cloud.githubusercontent.com/assets/7273443/15933279/6aec4f34-2e5f-11e6-9dc5-e370934f0714.png)

**Comment by garrensmith** [comment]
Good catch. I think I know what the issue is. We need to add the pouchdb-promise library in and remove the pouchdb/extras/promise. Would you like to do that or should I?

**Comment by ronyrun** [comment]
I can try :D 
let me do it now

**Comment by ronyrun** [comment]
bower                        ENOTFOUND Package pouchdb-promise not found

Do you know how I can add pouchdb-promise ?

**Comment by gimox** [comment]
+1 for a good solution

**Comment by nolanlawson** [comment]
This should be fixed in 0.10.0.

@ronyrun you may have to do another `npm install` in order to update dependencies

**Comment by ronyrun** [comment]
I tried with 0.10.0. as well I encounter the same error.

**Comment by nolanlawson** [comment]
Can you provide steps to reproduce? Our tests are passing against 5.4.x.

**Comment by garrensmith** [comment]
I think this is a bower issue. 

All misspelling thanks to my iPhone.




On Sun, Jun 12, 2016 at 8:55 PM +0200, "Nolan Lawson" <notifications@github.com> wrote:












Can you provide steps to reproduce? Our tests are passing against 5.4.x.

**Comment by gimox** [comment]
try with 0.10 but same error.

**Comment by ronyrun** [comment]
@nolanlawson do you know a CDN for the last version of pouchdb-find ? I'm trying to implement a jsbin to show you the error.

**Comment by garrensmith** [comment]
This should work https://npmcdn.com/pouchdb-find@0.10.0/dist/pouchdb.find.js

**Comment by nolanlawson** [comment]
Looks like we forgot to build before publishing to Bower. 10.0.1 ought to fix that.

**Comment by gimox** [comment]
updated but same error
```
pouchdb.find.min.js:2 Uncaught TypeError: Cannot read property 'Promise' of undefined(anonymous function) @ pouchdb.find.min.js:2r.44.28 @ pouchdb.find.min.js:2o @ pouchdb.find.min.js:1(anonymous function) @ pouchdb.find.min.js:1r.8.15 @ pouchdb.find.min.js:1o @ pouchdb.find.min.js:1(anonymous function) @ pouchdb.find.min.js:1r.14.11 @ pouchdb.find.min.js:1o @ pouchdb.find.min.js:1(anonymous function) @ pouchdb.find.min.js:1r.47.14 @ pouchdb.find.min.js:2o @ pouchdb.find.min.js:1t @ pouchdb.find.min.js:1(anonymous function) @ pouchdb.find.min.js:1(anonymous function) @ pouchdb.find.min.js:1(anonymous function) @ pouchdb.find.min.js:1
angular.js:13642*run* We are on the road. Application is started as: develop

```

**Comment by nolanlawson** [comment]
OK yeah I see this code hiding in `dist/pouchdb.find.js`:

```js
var PouchPromise;
/* istanbul ignore next */
if (typeof window !== 'undefined' && window.PouchDB) {
  PouchPromise = window.PouchDB.utils.Promise;
} else {
  PouchPromise = typeof global.Promise === 'function' ? global.Promise : _dereq_(28);
}
```

Not sure where it came from, but it needs to be corrected. I have to go to work; no time for this now unfortunately.

**Comment by gimox** [comment]
yeah. Waiting for fox...

**Comment by garrensmith** [comment]
I think its from here https://github.com/pouchdb/upsert/blob/master/index.js
I'll try and get a fix for it.

**Comment by cdata** [comment]
👍 just noticed this broke https://github.com/polymerelements/app-pouchdb

**Comment by jl-** [comment]
As PouchDB.utils, PouchDB.ajax, PouchDB.Errors are [deprecated](https://github.com/pouchdb/pouchdb/releases/tag/5.4.0) since pouchdb5.4.0,
guess I need to do this for now
```javascript
PouchDB.utils = { promise: require('pouchdb-promise') };
PouchDB.ajax = require('pouchdb-ajax');
PouchDB.Errors = require('pouchdb-errors');
```
Waiting for the fix

**Comment by garrensmith** [comment]
I've pushed 0.10.2 to npm. Could you all test that version. I'm not sure how to publish to bower. @nolanlawson could you publish to bower for me.

**Comment by nolanlawson** [comment]
Pushing to bower is just a matter of `npm version patch` and then `git push origin master --tags`. Bower works off of tags.

**Comment by garrensmith** [comment]
Great then it is deployed to bower as well

**Comment by nolanlawson** [comment]
Cool, checked the source and it seems `PouchDB.utils` is no longer used. Please reopen if not fixed. Thanks @garrensmith !
